version: '3.7'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=eMenu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    restart: on-failure
  redis:
    image: redis:alpine
    restart: on-failure
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  celery:
    build: ./backend
    command: celery -A backend worker -l info
    volumes:
      - ./backend/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  celery-beat:
    build: ./backend
    command: celery -A backend beat -l info
    volumes:
      - ./backend/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
volumes:
  postgres_data: